<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Faol',
    'Admin' => 'Admin',
    'Are you sure you want to delete this item?' => 'Haqiqatan ham bu elementni oʻchirib tashlamoqchimisiz?',
    'Auth Assignments' => '',
    'Auth Items' => '',
    'Auth Key' => '',
    'Back' => 'Orqaga',
    'Bollarini tanlang' => '',
    'Category' => 'Katagoriya',
    'Child' => '',
    'Code' => 'Kod',
    'Create' => 'Yaratish',
    'Create Auth Assignment' => '',
    'Create Auth Items' => '',
    'Create Hr Positions' => '',
    'Create Shifts' => '',
    'Created At' => 'Yaratilgan vaqti',
    'Created By' => 'Tomonidan yaratilgan',
    'Data' => 'Ma\'lumot',
    'Dataprizma-PLM' => 'Dataprizma-PLM',
    'Delete' => 'O\'chirish',
    'Deleted Successfully' => 'Muvaffaqqiyatili o\'chirildi',
    'Description' => 'Tavsif',
    'Email' => 'Elektron pochta',
    'End Time' => 'Tugash vaqti',
    'Fail' => 'Muvaffaqiyatsiz',
    'Fathername' => 'Otasining ismi',
    'Firstname' => 'Ism',
    'Foydalanuvchi uchun roll nomi' => '',
    'Hammasi belgilash' => '',
    'Haqiqatan ham ushbu mahsulotni yo\'q qilmoqchimisiz?' => '',
    'Haqiqatdan ham o\'chirmoqchimisiz?' => '',
    'Hatolik yuz berdi' => '',
    'Hr' => '',
    'Hr Department ID' => '',
    'Hr Organisation ID' => '',
    'Hr Position ID' => '',
    'Hr Positions' => '',
    'ID' => '',
    'Iltimos kuting!..' => '',
    'In name cannot be symbol "/" ' => '',
    'In name must be symbol "/" ' => '',
    'Inactive' => 'Faol emas',
    'Item Name' => '',
    'Lastname' => 'Familiya',
    'Name' => 'Nomi',
    'Name En' => 'Nomi En',
    'Name Ru' => 'Nomi Ru',
    'Name Uz' => 'Nomi Uz',
    'Parent' => '',
    'Password' => 'Parol',
    'Permissions' => 'Ruxsatlar',
    'Phone Number' => 'Telefon raqam',
    'Reset' => 'Qayta o\'rnatish',
    'Roles' => 'Rollar',
    'Roll nomi' => '',
    'Rule Name' => '',
    'Sana' => '',
    'Save' => 'Saqlash',
    'Saved' => 'Saqlangan',
    'Saved Successfully' => 'Muvaffaqqiyatli saqlandi',
    'Search' => 'Qidiruv',
    'Select_Category' => 'Kategoriyani tanlang',
    'Shifts' => '',
    'Slug' => 'Slug',
    'Start Time' => 'Boshlanish vaqti',
    'Status ID' => 'Holat',
    'Success' => 'Muvaffaqiyat',
    'The requested page does not exist.' => 'Talab qilingan sahifa mavjud emas.',
    'Token' => 'Token',
    'Type' => 'Turi',
    'Update' => 'Yangilash',
    'Update Auth Assignment: {name}' => '',
    'Update Auth Items: {name}' => '',
    'Update Hr Positions: {name}' => '',
    'Update Shifts: {name}' => '',
    'Updated At' => 'Yangilangan vaqti',
    'Updated By' => 'Tomonidan yangilangan',
    'User ID' => 'Foydalanuvchi',
    'Username' => 'Foydalanuvchi nomi',
    'Users' => 'Foydalanuvchilar',
    'View' => 'Ko\'rish',
    'Yangilash: {name}' => '',
    'welcome' => '',
];
