<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '',
    'Admin' => '',
    'Are you sure you want to delete this item?' => '',
    'Auth Assignments' => '',
    'Auth Items' => '',
    'Auth Key' => '',
    'Back' => '',
    'Bollarini tanlang' => '',
    'Category' => '',
    'Child' => '',
    'Code' => '',
    'Create' => '',
    'Create Auth Assignment' => '',
    'Create Auth Items' => '',
    'Create Hr Positions' => '',
    'Create Shifts' => '',
    'Created At' => '',
    'Created By' => '',
    'Data' => '',
    'Dataprizma-PLM' => '',
    'Delete' => '',
    'Deleted Successfully' => '',
    'Description' => '',
    'Email' => '',
    'End Time' => '',
    'Fail' => '',
    'Fathername' => '',
    'Firstname' => '',
    'Foydalanuvchi uchun roll nomi' => '',
    'Hammasi belgilash' => '',
    'Haqiqatan ham ushbu mahsulotni yo\'q qilmoqchimisiz?' => '',
    'Haqiqatdan ham o\'chirmoqchimisiz?' => '',
    'Hatolik yuz berdi' => '',
    'Hr' => '',
    'Hr Department ID' => '',
    'Hr Organisation ID' => '',
    'Hr Position ID' => '',
    'Hr Positions' => '',
    'ID' => '',
    'Iltimos kuting!..' => '',
    'In name cannot be symbol "/" ' => '',
    'In name must be symbol "/" ' => '',
    'Inactive' => '',
    'Item Name' => '',
    'Lastname' => '',
    'Name' => '',
    'Name En' => '',
    'Name Ru' => '',
    'Name Uz' => '',
    'Parent' => '',
    'Password' => '',
    'Permissions' => '',
    'Phone Number' => '',
    'Reset' => '',
    'Roles' => '',
    'Roll nomi' => '',
    'Rule Name' => '',
    'Sana' => '',
    'Save' => 'Saqlash',
    'Saved' => 'Saqlangan',
    'Saved Successfully' => 'Muvaffaqqiyatli saqlandi',
    'Search' => '',
    'Select_Category' => '',
    'Shifts' => '',
    'Slug' => '',
    'Start Time' => '',
    'Status ID' => '',
    'Success' => '',
    'The requested page does not exist.' => '',
    'Token' => '',
    'Type' => '',
    'Update' => '',
    'Update Auth Assignment: {name}' => '',
    'Update Auth Items: {name}' => '',
    'Update Hr Positions: {name}' => '',
    'Update Shifts: {name}' => '',
    'Updated At' => '',
    'Updated By' => '',
    'User ID' => '',
    'Username' => '',
    'Users' => '',
    'View' => '',
    'Yangilash: {name}' => '',
    'welcome' => '',
];
