export const items = {
    id: "",
    processing_time_id: "",
    equipment_group_id: "",
    start_work: "",
    end_work: "",
    planned_stops: [],
    unplanned_stops: [],
    equipmentGroup: {
        equipments: [],
        product_list: [],
    },
    products: [{
        label: "",
        value: "",
        qty: "",
        fact_qty: "",
        product_id: "",
        lifecycle: "",
        bypass: "",
        target_qty: 0,
        product_lifecycle_id: "",
        repaired: [],
        scrapped: [],
    }],
    equipments: [],
    is_change: true,
};